version: '3.4'

services:
  ci-build:
    image: microsoft/dotnet:2.2-aspnetcore-runtime
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ShowScraper.Api/ShowScraper.Api.csproj && dotnet publish ./ShowScraper.Api.csproj -c Release -o ./obj/Docker/publish"
